apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: kubsets
spec:
  selector:
    matchLabels:
      app: node-agent
  template:
    metadata:
      labels:
        app: node-agent
    spec:
      containers:
        - name: agent
          image: busybox:1.36
          command: ["sh", "-c", "while true; do echo node-agent $(hostname) alive; sleep 30; done"]
